### ISSUE TITLE
suggested readme enhancement - tutorial?

### ISSUE THREAD

**Issue by fossfreedom** [TheBigW/DRC#7]
As an aside - maybe the README should have a step by step guide showing how to setup an example digital-room-correction setup.

e.g.

step 1: select your input and output sound devices
step 2: click "measure" - it stays greyed out for me ... I suppose something is to enable the button - is it because I'm using 16bit audio?
step 3: define your calculation filter (what are we calculating?)
step 4: define your filter (not obvious what we are doing here)
step 5: click apply (so what happens now?)

I've just been randomly choosing stuff not really understanding how the various options influence the end result

**Comment by TheBigW** [comment]
hardest part to describe this and write a usable docu... I attempted an update to the readme now. 

Hopefully it is clearer. In order to test I could provide you a measured file as well a final filter (where to upload?). For measuring 32bit audio is needed and most usable measurement equipment provides this.
